# Generated by Django 4.2.23 on 2025-11-28 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.TextField(max_length=500)),
                ('title_id', models.IntegerField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='eveonline.evecorporationinfo')),
            ],
            options={
                'unique_together': {('corp', 'title_id')},
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pull', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_token', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esi_title_mapping', to='auth.group')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_titles', to='eveonline.evecorporationinfo')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unistudent.title')),
            ],
            options={
                'unique_together': {('corp',)},
            },
        ),
    ]
